#!/bin/bash
set -x

if rg -t rust 'TODO|TOOD|LATER|\\todo|todo!|dbg!'; then
    echo "You have TODO-s"
    exit 1
fi

set -e
cargo clippy -- --no-deps -Dwarnings -Aclippy::uninlined_format_args
RUSTDOCFLAGS=-Dwarnings cargo doc

